ports:
  - port: 8080
    onOpen: open-preview
checkoutLocation: "go/src/github.com/demo-apps/go-gin-app"
workspaceLocation: "go/src/github.com/demo-apps/go-gin-app"
tasks:
  - init: >
      go install github.com/mitranim/gow@latest
    command: >
      gow test -v
github:
    prebuilds:
        pullRequestsFromForks: true
vscode:
  extensions:
    - golang.go

